const defaults = {
  privacyAngle: 'PDFOmni processes files in your browser, so the document bytes stay on your device instead of being uploaded to a remote PDF server.',
  advanced: 'After finishing this tool, you can continue into other PDFOmni workflows such as editing, signing, redacting, compressing, or using the AI Copilot with local document context.',
  safetyFaq: {
    question: 'Is it safe to use this PDF tool online?',
    answer: 'Yes. The core PDF workflow runs locally in your browser, so your PDF is processed on your device and is not uploaded by PDFOmni for server-side handling.',
  },
}

export const toolSeo = {
  merge: {
    h1: 'Merge PDF Files Locally - Fast, Free, and Private',
    intro: 'Combine multiple PDF files into a single organized document without sending them to a server. The merge tool is built for quick browser-based document assembly, whether you are joining reports, receipts, scans, contracts, or school files.',
    steps: ['Select or drag two or more PDF files into the upload area.', 'Review the file order and rearrange the documents if needed.', 'Export one combined PDF directly from your browser session.'],
    why: 'Because the merge happens locally, you avoid the slow upload-and-wait flow common on server-based PDF sites. Large files can be joined without exposing confidential pages to a remote processor.',
    advanced: 'Once the merged file is ready, you can move into page reordering, compression, signing, watermarking, or AI Copilot analysis without leaving the PDFOmni workspace.',
    useCases: ['Combining signed forms into one packet', 'Joining scanned receipts for expense reports', 'Merging project chapters or client deliverables'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can I change the order before merging?', answer: 'Yes. Add the PDFs, arrange them in the order you want, and then export the final merged document.' },
      { question: 'Does merging reduce PDF quality?', answer: 'No intentional quality reduction is applied. Pages are copied into one file, so the original visual content is preserved as much as the browser PDF engine allows.' },
    ],
  },
  split: {
    h1: 'Split PDF Pages Locally - Extract Pages Without Uploads',
    intro: 'Split a PDF into smaller files or extract only the pages you need. This is useful when a long PDF contains one section, invoice, chapter, or form that needs to be shared separately.',
    steps: ['Drop your PDF into the upload box.', 'Enter the page range or choose the pages you want to extract.', 'Download the split PDF output instantly.'],
    why: 'The page extraction happens on your computer, so sensitive pages are not sent through an upload queue. You get fast page splitting while keeping the original PDF private.',
    advanced: 'After splitting a document, you can compress the extracted pages, add page numbers, sign the result, or use the AI Copilot to summarize just the smaller section.',
    useCases: ['Extracting one chapter from an ebook or manual', 'Sharing only selected contract pages', 'Creating smaller PDFs from large scans'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can I split only specific page ranges?', answer: 'Yes. Use page ranges to export the exact pages you need instead of saving the full document.' },
      { question: 'Will the original PDF be changed?', answer: 'No. PDFOmni creates a new output file in your browser and leaves the original file untouched.' },
    ],
  },
  reorder: {
    h1: 'Reorder PDF Pages Privately in Your Browser',
    intro: 'Rearrange PDF pages with a simple drag-and-drop workflow. It is designed for fixing scanned documents, moving cover pages, sorting appendices, and cleaning up page order before sharing.',
    steps: ['Upload your PDF locally in the browser.', 'Drag pages into the correct order in the page grid.', 'Download the reordered PDF file.'],
    why: 'Reordering pages should not require uploading a confidential document. PDFOmni keeps the page arrangement process local so you can correct files quickly and privately.',
    advanced: 'When the page order is right, you can continue with compression, watermarking, signing, page numbering, or AI-assisted review inside the same PDF toolkit.',
    useCases: ['Fixing scans that were saved out of order', 'Moving a cover sheet to the front', 'Preparing packets before emailing or printing'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can I reorder every page manually?', answer: 'Yes. The tool is built around page thumbnails so you can move pages into the exact sequence you want.' },
      { question: 'Does reordering delete any pages?', answer: 'No. Reordering changes the page sequence in the exported copy unless you intentionally use another tool to remove pages.' },
    ],
  },
  compress: {
    h1: 'Compress PDF Files Locally - Reduce Size Without Uploading',
    intro: 'Compress PDF files to make them easier to email, upload, archive, or share. The compressor runs in the browser and focuses on reducing file size while giving you control over the output target.',
    steps: ['Select your PDF from the upload area.', 'Choose a compression target or quality level.', 'Download the optimized PDF when the analysis and compression finish.'],
    why: 'Server compressors require uploading the whole document before any optimization starts. PDFOmni keeps the work on your device, which is especially helpful for private files, large PDFs, and slow connections.',
    advanced: 'After compression, you can use PDFOmni to merge the smaller file with other documents, redact sensitive information, add a signature, or ask the AI Copilot about the compressed PDF content.',
    useCases: ['Shrinking PDFs for email attachments', 'Meeting upload size limits on forms and portals', 'Reducing local storage used by large scanned files'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Will compressing a PDF ruin the quality?', answer: 'Compression can reduce image detail depending on the target size, but you can choose settings that balance quality and file size.' },
      { question: 'Can I compress a large PDF?', answer: 'Yes, though very large documents depend on your browser memory and device performance because the work happens locally.' },
    ],
  },
  rotate: {
    h1: 'Rotate PDF Pages Online - Local and Secure',
    intro: 'Rotate sideways or upside-down PDF pages directly in your browser. This is useful for scanned documents, phone photos saved as PDFs, or mixed-orientation files that need quick cleanup.',
    steps: ['Upload the PDF you want to rotate.', 'Choose individual pages or apply rotation to the full document.', 'Export a corrected PDF with the new page orientation.'],
    why: 'Rotation is handled locally, so you do not have to upload personal IDs, forms, scans, or contracts just to fix orientation. The output is created from your browser session.',
    advanced: 'After rotating pages, you can reorder them, add page numbers, compress the corrected file, or continue into signing and editing tools.',
    useCases: ['Correcting scanned pages from a copier', 'Fixing phone-generated PDFs', 'Preparing mixed-orientation documents for printing'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can I rotate only one page?', answer: 'Yes. You can rotate selected pages instead of applying the same change to the whole PDF.' },
      { question: 'Does rotation affect text selection?', answer: 'The page orientation is updated in the exported PDF while preserving the document content as much as possible.' },
    ],
  },
  'page-numbers': {
    h1: 'Add Page Numbers to a PDF Locally',
    intro: 'Add clear page numbers to reports, packets, drafts, and long PDFs without uploading the document. Page numbering helps readers reference sections and keeps printed files easier to navigate.',
    steps: ['Upload your PDF into the browser.', 'Choose the numbering style, position, and starting number.', 'Download the PDF with page numbers applied.'],
    why: 'PDFOmni applies page numbers locally, so internal reports, legal packets, and private drafts do not need to leave your computer for a simple formatting change.',
    advanced: 'You can combine page numbering with merging, reordering, watermarking, signing, or compression to prepare a polished final document.',
    useCases: ['Numbering client packets before review', 'Adding references to study notes or manuals', 'Preparing PDFs for printing and physical binders'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can I choose where page numbers appear?', answer: 'Yes. Use the page number settings to place numbering where it fits your document layout.' },
      { question: 'Can page numbers start from a custom number?', answer: 'Yes. The tool supports changing the starting number for documents that continue from another file.' },
    ],
  },
  'word-to-pdf': {
    h1: 'Convert Word to PDF in Your Browser',
    intro: 'Convert DOCX documents into PDF files locally for easier sharing, printing, and archiving. The tool is designed for quick document conversion without a server upload step.',
    steps: ['Choose a Word document from your device.', 'Let the browser prepare the PDF output.', 'Download the converted PDF file.'],
    why: 'Local conversion helps keep drafts, resumes, internal memos, and client documents private. You avoid sending the source Word file to a remote converter just to create a PDF.',
    advanced: 'After conversion, you can merge the PDF with attachments, compress it, add page numbers, watermark it, or use AI Copilot to inspect the resulting document.',
    useCases: ['Saving resumes and letters as PDFs', 'Preparing DOCX reports for upload portals', 'Creating shareable copies of office documents'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Does the Word file upload to a server?', answer: 'No. PDFOmni performs the conversion in the browser as part of its local-first PDF workflow.' },
      { question: 'Will complex formatting always match perfectly?', answer: 'Most common document layouts convert well, but very complex Word features can vary depending on browser rendering support.' },
    ],
  },
  'excel-to-pdf': {
    h1: 'Convert Excel to PDF Privately',
    intro: 'Turn spreadsheets into PDF documents for sharing, printing, or submitting. The Excel to PDF tool keeps the workflow local while making tabular data easier to distribute.',
    steps: ['Upload an Excel or CSV file.', 'Preview or prepare the spreadsheet output.', 'Download the finished PDF from your browser.'],
    why: 'Spreadsheets often contain financial, customer, or operational details. Local conversion helps you create PDF copies without sending workbook data to a third-party server.',
    advanced: 'Once the spreadsheet is a PDF, you can compress it, add a watermark, merge it into a report, or open it in the editor for additional markup.',
    useCases: ['Exporting invoices or budgets', 'Sharing read-only spreadsheet reports', 'Preparing tables for email or print'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can I convert CSV files too?', answer: 'Yes. The tool accepts common spreadsheet formats including CSV where supported by the app workflow.' },
      { question: 'Will formulas remain editable?', answer: 'No. The output is a PDF view of the spreadsheet, so formulas become document content rather than editable spreadsheet cells.' },
    ],
  },
  'image-to-pdf': {
    h1: 'Convert Images to PDF Locally',
    intro: 'Create a PDF from JPG, PNG, WebP, BMP, or similar image files. This is useful for turning photos, receipts, scans, screenshots, and design exports into one shareable PDF.',
    steps: ['Select one or more images from your device.', 'Arrange the images in the order you want.', 'Export them as a single PDF file.'],
    why: 'Image-to-PDF conversion runs in the browser, so photos of private documents or receipts do not need to be uploaded to a cloud converter.',
    advanced: 'After creating the PDF, you can merge it with other files, compress it, add page numbers, or use the editor to place text, shapes, and signatures.',
    useCases: ['Combining receipt photos into one file', 'Turning screenshots into a PDF handout', 'Creating PDF scans from phone images'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can I convert multiple images at once?', answer: 'Yes. Add multiple images and export them together as one PDF.' },
      { question: 'Will the image quality change?', answer: 'The PDF uses your image data, though final file size and display quality can depend on image dimensions and browser processing.' },
    ],
  },
  'html-to-pdf': {
    h1: 'Convert HTML to PDF in the Browser',
    intro: 'Turn pasted HTML or uploaded HTML files into PDF documents. It is a quick way to save web content, templates, receipts, or simple reports as portable files.',
    steps: ['Paste HTML content or upload an HTML file.', 'Preview or prepare the document in the browser.', 'Download the generated PDF.'],
    why: 'HTML conversion is handled locally, which keeps draft templates and internal content away from server-side converters. It also removes the delay of uploading source files first.',
    advanced: 'The generated PDF can be compressed, merged, signed, watermarked, or reviewed with other PDFOmni tools after conversion.',
    useCases: ['Saving simple web templates as PDFs', 'Creating printable HTML reports', 'Archiving receipts or generated pages'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can I upload an HTML file?', answer: 'Yes. You can paste HTML or use the upload mode for local HTML files.' },
      { question: 'Will external website styling always load?', answer: 'External assets can depend on browser access and CORS rules, so self-contained HTML usually produces the most reliable result.' },
    ],
  },
  'pdf-to-image': {
    h1: 'Convert PDF Pages to Images Locally',
    intro: 'Export PDF pages as image files for previews, thumbnails, presentations, or quick sharing. The conversion is done on your device through the browser.',
    steps: ['Upload the PDF you want to convert.', 'Choose image settings and page output options.', 'Download the exported images.'],
    why: 'Because pages are rendered locally, you can convert private PDFs into images without uploading the document to a remote rendering service.',
    advanced: 'After exporting images, you can also convert images back into a new PDF, compress the original file, or use AI Copilot to summarize the source document.',
    useCases: ['Creating thumbnails for documents', 'Exporting pages for presentations', 'Saving PDF pages as shareable images'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can I convert every page?', answer: 'Yes. You can export pages from the PDF as images depending on the selected settings.' },
      { question: 'What image formats are supported?', answer: 'PDFOmni supports common browser image output formats such as PNG or JPG where available in the tool.' },
    ],
  },
  'pdf-to-text': {
    h1: 'Extract Text from PDF Files Privately',
    intro: 'Copy text out of PDF files without sending the document to an extraction service. This is useful for notes, quotes, reports, research, and quick content reuse.',
    steps: ['Upload a PDF with selectable text.', 'Let PDFOmni extract the document text locally.', 'Copy or download the extracted text output.'],
    why: 'Text extraction can involve sensitive contracts, records, or research files. Running the extraction locally keeps the PDF content in your browser session.',
    advanced: 'You can combine extracted text with AI Copilot analysis, convert pages to images, or use other PDFOmni tools to prepare the original document for sharing.',
    useCases: ['Pulling text from reports or manuals', 'Saving notes from PDFs', 'Copying content for search and review'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Does this work on scanned PDFs?', answer: 'It works best on PDFs with embedded selectable text. Scanned image-only PDFs may need OCR before reliable text extraction.' },
      { question: 'Will formatting be preserved?', answer: 'The tool focuses on extracting readable text, so complex layout and columns may not match the original PDF exactly.' },
    ],
  },
  watermark: {
    h1: 'Add a Watermark to PDF Files Locally',
    intro: 'Place text watermarks on PDF pages for drafts, approvals, internal reviews, or ownership marks. The watermark is applied in your browser without uploading the PDF.',
    steps: ['Upload the PDF you want to watermark.', 'Enter your watermark text and choose placement or style settings.', 'Export the watermarked PDF.'],
    why: 'Watermarking often applies to private drafts, business documents, or client work. PDFOmni keeps those files local while still giving you a quick branding and labeling workflow.',
    advanced: 'After watermarking, you can compress the result, sign it, merge it with other documents, or redact sensitive sections before sharing.',
    useCases: ['Marking PDFs as draft or confidential', 'Adding a company or project label', 'Preparing review copies for clients'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can I customize the watermark text?', answer: 'Yes. You can enter the text you want and adjust the available watermark settings before exporting.' },
      { question: 'Does the watermark apply to every page?', answer: 'The tool is designed for applying watermark text across the PDF according to the selected settings.' },
    ],
  },
  redact: {
    h1: 'Redact PDF Content Securely in Your Browser',
    intro: 'Black out sensitive areas of a PDF and export a version intended for safer sharing. Use it for names, IDs, account numbers, addresses, and other private details.',
    steps: ['Upload your PDF locally.', 'Draw redaction boxes over the content you want to remove.', 'Export a redacted PDF copy.'],
    why: 'Redaction is privacy-sensitive by nature. PDFOmni keeps the workflow local so the unredacted source document is not uploaded to a server during processing.',
    advanced: 'After redaction, you can compress the safe copy, add a watermark, sign it, or use page tools to remove unrelated pages before sending.',
    useCases: ['Removing personal data before sharing', 'Preparing public copies of records', 'Hiding financial or legal details'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Is the redacted text still copyable?', answer: 'The redaction workflow is designed to remove covered text from the exported PDF rather than simply placing a visual box over it.' },
      { question: 'Should I review the exported file?', answer: 'Yes. Always open and inspect the exported PDF before sharing any redacted document.' },
    ],
  },
  crop: {
    h1: 'Crop PDF Pages Locally and Privately',
    intro: 'Crop PDF page edges to remove margins, scanner borders, headers, footers, or unwanted whitespace. The crop tool is useful for cleaning scanned files and focusing a page layout.',
    steps: ['Upload the PDF you want to crop.', 'Set the crop box visually or with available controls.', 'Download the cropped PDF copy.'],
    why: 'Cropping happens in the browser, so private scans and internal files do not need to be uploaded just to adjust page boundaries.',
    advanced: 'After cropping, you can rotate pages, compress the result, add page numbers, or open the file in the editor for text and shape annotations.',
    useCases: ['Removing scanner borders', 'Trimming whitespace around pages', 'Preparing cleaner PDFs for print or upload'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Does cropping delete the original file?', answer: 'No. PDFOmni exports a new cropped copy and does not modify the original PDF on your device.' },
      { question: 'Can I apply the same crop to multiple pages?', answer: 'The crop workflow supports applying crop settings across pages where the tool controls allow it.' },
    ],
  },
  encrypt: {
    h1: 'Protect PDF Files with a Password Locally',
    intro: 'Add password protection to a PDF before sharing or archiving it. The protect tool helps restrict access to documents that need an extra layer of security.',
    steps: ['Upload the PDF you want to protect.', 'Enter and confirm the password settings.', 'Download the password-protected PDF.'],
    why: 'Password protection is applied in the browser, so you do not have to give an unprotected copy of the file to a server before securing it.',
    advanced: 'After protecting a PDF, you can keep using PDFOmni to organize other documents, compress safe copies, or prepare a signed version for distribution.',
    useCases: ['Securing forms before email', 'Protecting client documents', 'Adding a password to archived records'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can PDFOmni recover the password later?', answer: 'No. Keep your password somewhere safe because PDFOmni does not store it for you.' },
      { question: 'Is password protection the same as encryption?', answer: 'Password protection uses PDF security features to restrict access, but you should still share passwords carefully.' },
    ],
  },
  decrypt: {
    h1: 'Unlock PDF Files Locally When You Know the Password',
    intro: 'Remove password protection from PDFs you are allowed to access. This helps when you need a copy that is easier to archive, merge, print, or process.',
    steps: ['Upload the protected PDF.', 'Enter the correct password in your browser.', 'Download the unlocked PDF copy.'],
    why: 'Unlocking happens locally, so the protected file and password do not need to be sent to a remote unlock service.',
    advanced: 'After unlocking, you can merge, split, compress, redact, sign, or analyze the document with PDFOmni tools.',
    useCases: ['Preparing owned files for archiving', 'Removing protection from internal documents', 'Making a document easier to merge or compress'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can this unlock a PDF without the password?', answer: 'No. You need the correct password and the right to access the document.' },
      { question: 'Is the original protected PDF changed?', answer: 'No. The tool creates a new unlocked output file and leaves the original untouched.' },
    ],
  },
  sign: {
    h1: 'Sign PDF Files Locally in Your Browser',
    intro: 'Add a signature image to PDF documents without uploading them. This is built for quick approvals, forms, acknowledgements, and lightweight signing workflows.',
    steps: ['Upload the PDF you need to sign.', 'Add or place your signature image on the page.', 'Export the signed PDF file.'],
    why: 'Signing often involves personal or business documents. PDFOmni keeps the PDF and signature asset in your browser session instead of sending them to a signing server.',
    advanced: 'After signing, you can compress the final PDF, merge it with supporting documents, or watermark a review copy.',
    useCases: ['Signing forms and acknowledgements', 'Adding approval marks to documents', 'Preparing PDFs for email submission'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Is this a cryptographic digital signature?', answer: 'This tool is for placing a visual signature image, not for certificate-based digital signing.' },
      { question: 'Can I move the signature before exporting?', answer: 'Yes. Place and adjust the signature visually before downloading the signed PDF.' },
    ],
  },
  batch: {
    h1: 'Batch Process PDF Files Locally',
    intro: 'Process multiple PDFs in one workflow instead of repeating the same action file by file. Batch processing is useful for repetitive document cleanup and preparation tasks.',
    steps: ['Upload the PDFs you want to process together.', 'Choose the batch action and settings.', 'Download the processed output files.'],
    why: 'Batch work can involve many private documents. PDFOmni keeps the processing local so you can handle groups of files without sending them through a server queue.',
    advanced: 'Use batch processing with other PDFOmni workflows such as compression, protection, page organization, or AI-assisted document review when you need a larger document pipeline.',
    useCases: ['Preparing many PDFs for upload', 'Applying repeated cleanup steps', 'Processing document sets for a client or class'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can I process multiple files at once?', answer: 'Yes. The batch tool is built for handling more than one PDF in a single workflow.' },
      { question: 'Will batch processing be slower on large files?', answer: 'It can be, because the work uses your browser and device resources instead of a remote server.' },
    ],
  },
  wcag: {
    h1: 'Check PDF Accessibility Locally',
    intro: 'Run a PDF accessibility-oriented check to identify issues that may affect readers using assistive technology. It helps you review documents before publishing or sharing them widely.',
    steps: ['Upload the PDF you want to inspect.', 'Run the accessibility check in the browser.', 'Review the findings and decide what needs fixing.'],
    why: 'Accessibility review can involve unpublished or internal files. A local-first check lets you inspect documents without uploading draft content to a third-party scanner.',
    advanced: 'After reviewing issues, you can use PDFOmni tools to edit, add text, organize pages, compress the file, or prepare a corrected version for distribution.',
    useCases: ['Checking public documents before upload', 'Reviewing forms and reports', 'Finding accessibility problems in shared PDFs'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Does this guarantee WCAG compliance?', answer: 'No automated check can guarantee full compliance. Use the results as a practical review aid alongside manual inspection.' },
      { question: 'Can it fix accessibility issues automatically?', answer: 'The checker identifies issues; depending on the result, you may need to edit the document or source file.' },
    ],
  },
}

export function getToolSeo(id, tool) {
  return toolSeo[id] || {
    h1: `${tool.name} Locally - Private Browser-Based PDF Tool`,
    intro: `${tool.description}. PDFOmni keeps the workflow local in your browser so common PDF tasks can be completed without uploading documents to a server.`,
    steps: ['Upload your PDF in the tool interface.', 'Choose the settings that match your document workflow.', 'Download the finished PDF output.'],
    why: defaults.privacyAngle,
    advanced: defaults.advanced,
    useCases: ['Preparing documents for email', 'Cleaning files before sharing', 'Handling private PDFs on your own device'],
    faqs: [defaults.safetyFaq],
  }
}
